"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import DOMPurify from "dompurify";
import { useTheme } from "@/components/theme-provider";

interface EmailRendererProps {
  /** Sanitized HTML content from backend. */
  html?: string | null;
  /** Plain text fallback. */
  plainText?: string | null;
  /** Whether remote images are allowed. */
  imagesAllowed?: boolean;
}

/** Which canvas a message body renders on -- see pickCanvas below. */
type Canvas = "light" | "dark";

/**
 * The canvas a given message body renders on.
 *
 * Message HTML is written by senders against a light canvas, and a great
 * deal of it supplies its own white background while leaving body text
 * uncoloured. `color` inherits through the shadow boundary, so a dark
 * canvas there puts light text on the sender's own white background and
 * the message cannot be read. Nothing in the styles below can be resolved
 * the other way either: a link colour, a quote colour and a code
 * background chosen for a dark canvas all land on that same white. So
 * markup that was not authored here always gets the light canvas, whatever
 * the application theme is.
 *
 * The plain-text wrapper is generated by this component and carries no
 * colours of its own, so it follows the theme like the rest of the
 * interface.
 */
function pickCanvas(hasHtml: boolean, theme: Canvas): Canvas {
  return hasHtml ? "light" : theme;
}

/** CSS injected into the Shadow DOM for email rendering. */
function getEmailStyles(canvas: Canvas): string {
  const isDark = canvas === "dark";
  return `
    :host {
      display: block;
      /* A shadow root isolates styles but does not create a containing
         block on its own, so position: fixed in a message would resolve
         against the viewport rather than this box -- covering the whole
         application regardless of what the server-side sanitizer catches.
         Layout containment makes the host itself that containing block,
         confining any such declaration to the message pane it belongs to. */
      contain: layout paint;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      font-size: 14px;
      line-height: 1.6;
      word-wrap: break-word;
      overflow-wrap: break-word;
      color: ${isDark ? "#e4e4e7" : "#18181b"};
      background: ${isDark ? "#09090b" : "#ffffff"};
    }
    img {
      max-width: 100%;
      height: auto;
    }
    a {
      color: ${isDark ? "#60a5fa" : "#2563eb"};
    }
    table {
      max-width: 100%;
      border-collapse: collapse;
    }
    td, th {
      padding: 4px 8px;
    }
    blockquote {
      border-left: 3px solid ${isDark ? "#3f3f46" : "#d4d4d8"};
      margin: 0.5em 0;
      padding: 0.25em 1em;
      color: ${isDark ? "#a1a1aa" : "#71717a"};
    }
    pre {
      background: ${isDark ? "#18181b" : "#f4f4f5"};
      padding: 8px 12px;
      border-radius: 4px;
      overflow-x: auto;
      font-size: 13px;
    }
    hr {
      border: none;
      border-top: 1px solid ${isDark ? "#27272a" : "#e4e4e7"};
      margin: 1em 0;
    }
  `;
}

/**
 * Strip remote images from HTML unless allowed.
 * Preserves inline data: URIs and cid: references.
 */
function stripRemoteImages(html: string): {
  html: string;
  hadRemoteImages: boolean;
} {
  let hadRemoteImages = false;
  const stripped = html.replace(
    /<img\b[^>]*\bsrc\s*=\s*["']?(https?:\/\/[^"'\s>]+)["']?[^>]*\/?>/gi,
    () => {
      hadRemoteImages = true;
      return "";
    },
  );
  return { html: stripped, hadRemoteImages };
}

/** Escape every character that can change the meaning of markup.
 *
 * Quotes matter as much as angle brackets here: the linkifier below places a
 * matched URL inside an href attribute, so an unescaped quote closes that
 * attribute and everything after it is parsed as further attributes -- which
 * is an event handler if the sender wants one.
 */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Linkify URLs in already-escaped plain text. */
export function linkifyText(escaped: string): string {
  // Stops at a quote entity as well as whitespace, so a URL cannot swallow
  // the boundary of the attribute it is about to be placed in.
  const urlPattern = /(https?:\/\/(?:(?!&quot;|&#39;|&lt;|&gt;)[^\s<>"'])+)/g;
  return escaped.replace(
    urlPattern,
    '<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>',
  );
}

/**
 * Renders email HTML content in an isolated Shadow DOM.
 *
 * Uses Shadow DOM for complete CSS isolation (same approach as mail0).
 * Falls back to linkified plain text when no HTML is available.
 */
export function EmailRenderer({
  html,
  plainText,
  imagesAllowed = false,
}: EmailRendererProps) {
  const hostRef = useRef<HTMLDivElement>(null);
  const shadowRootRef = useRef<ShadowRoot | null>(null);
  const { resolvedTheme } = useTheme();
  const [hasBlockedImages, setHasBlockedImages] = useState(false);

  // Attach Shadow DOM once
  useEffect(() => {
    if (!hostRef.current || shadowRootRef.current) return;
    shadowRootRef.current = hostRef.current.attachShadow({ mode: "open" });
  }, []);

  // Render content into Shadow DOM
  useEffect(() => {
    if (!shadowRootRef.current) return;

    let content: string;

    if (html) {
      // Client-side sanitization as defense-in-depth (backend uses nh3)
      let processedHtml = DOMPurify.sanitize(html, {
        ALLOW_UNKNOWN_PROTOCOLS: false,
        ALLOWED_TAGS: [
          "a", "abbr", "address", "article", "b", "blockquote", "br",
          "caption", "center", "cite", "code", "col", "colgroup", "dd",
          "del", "details", "dfn", "div", "dl", "dt", "em", "figcaption",
          "figure", "font", "footer", "h1", "h2", "h3", "h4", "h5", "h6",
          "header", "hr", "i", "img", "ins", "kbd", "li", "main", "mark",
          "nav", "ol", "p", "pre", "q", "s", "section", "small", "span",
          "strong", "sub", "summary", "sup", "table", "tbody", "td",
          "tfoot", "th", "thead", "tr", "u", "ul", "wbr",
        ],
        ALLOWED_ATTR: [
          "align", "alt", "border", "cellpadding", "cellspacing", "class",
          "color", "colspan", "dir", "face", "height", "href", "hspace",
          "id", "lang", "role", "rowspan", "size", "src", "style",
          "summary", "target", "title", "type", "valign", "vspace", "width",
        ],
      });

      if (!imagesAllowed) {
        const result = stripRemoteImages(processedHtml);
        processedHtml = result.html;
        setHasBlockedImages(result.hadRemoteImages);
      } else {
        setHasBlockedImages(false);
      }

      content = processedHtml;
    } else if (plainText) {
      // Render plain text with preserved whitespace and linkified URLs
      // Sanitized like the HTML path rather than trusted for being "just
      // text": everything here is still assigned through innerHTML, so an
      // escaping mistake in the linkifier would be an injection rather than
      // a rendering glitch.
      const linked = linkifyText(escapeHtml(plainText));
      content = DOMPurify.sanitize(
        `<pre style="white-space: pre-wrap; font-family: inherit; margin: 0;">${linked}</pre>`,
        {
          ALLOW_UNKNOWN_PROTOCOLS: false,
          ALLOWED_TAGS: ["pre", "a", "br"],
          ALLOWED_ATTR: ["href", "target", "rel", "style"],
        },
      );
    } else {
      content = '<p style="color: #71717a; font-style: italic;">No content available</p>';
    }

    const styles = getEmailStyles(pickCanvas(Boolean(html), resolvedTheme));
    shadowRootRef.current.innerHTML = `<style>${styles}</style>${content}`;
  }, [html, plainText, imagesAllowed, resolvedTheme]);

  // Handle link clicks to open in new tab
  useEffect(() => {
    if (!shadowRootRef.current) return;
    const root = shadowRootRef.current;

    const handleClick = (e: Event) => {
      const target = e.target as HTMLElement;
      const anchor = target.closest("a");
      if (anchor) {
        e.preventDefault();
        const href = anchor.getAttribute("href");
        if (
          href &&
          (href.startsWith("http://") || href.startsWith("https://"))
        ) {
          window.open(href, "_blank", "noopener,noreferrer");
        } else if (href && href.startsWith("mailto:")) {
          window.location.href = href;
        }
      }
    };

    const handleImageError = (e: Event) => {
      const target = e.target as HTMLImageElement;
      if (target.tagName === "IMG") {
        target.style.display = "none";
      }
    };

    root.addEventListener("click", handleClick);
    root.addEventListener("error", handleImageError, true);

    return () => {
      root.removeEventListener("click", handleClick);
      root.removeEventListener("error", handleImageError, true);
    };
  }, [html, plainText]);

  return (
    <div className="flex flex-col">
      {hasBlockedImages && (
        <div className="flex items-center gap-2 bg-amber-500/10 px-4 py-2 text-sm text-amber-600 dark:text-amber-400">
          <span>Remote images have been blocked for privacy.</span>
        </div>
      )}
      <div
        ref={hostRef}
        data-testid="email-body"
        className="min-h-0 flex-1 overflow-auto px-4 py-2"
      />
    </div>
  );
}
